version: "3.3"
services:
  mongo_provision_dev:
    build: ./database/provision/dev
    links:
     - mongodb_dev

  mongodb_dev:
    image: mongo
    ports:
      - "27017:27017"
      - "28017:28017"

  node_backend:
    build: ./app
    image: node_backend
    ports:
      - 3001:3001
    environment:
      - MONGODB_HOST=mongodb_dev
      - MONGODB_PORT=27017
      - TEST_MONGODB_HOST=mongodb_test
      - TEST_MONGODB_PORT=27018
      - PORT=3001
